/** Scholastic Ledger dashboard: Bengali-first, local-first, intentionally simple. */
const KEY='spt-dashboard-v5-data',OLD='spt-merge-demo-data-v1',SUBJECTS=['বাংলা','বাংলা ১ম পত্র','বাংলা ২য় পত্র','ইংরেজি','ইংরেজি ১ম পত্র','ইংরেজি ২য় পত্র','গণিত','উচ্চতর গণিত','বিজ্ঞান','পদার্থবিজ্ঞান','রসায়ন','জীববিজ্ঞান','তথ্য ও যোগাযোগ প্রযুক্তি','বাংলাদেশ ও বিশ্বপরিচয়','ইতিহাস','ভূগোল','হিসাববিজ্ঞান','কৃষিশিক্ষা','চারু ও কারুকলা','শারীরিক শিক্ষা','আরবি','কুরআন মাজীদ ও তাজভীদ','ইসলাম ও নৈতিক শিক্ষা','হিন্দুধর্ম ও নৈতিক শিক্ষা','বৌদ্ধধর্ম ও নৈতিক শিক্ষা','খ্রিস্টধর্ম ও নৈতিক শিক্ষা'];
const $=(s,r=document)=>r.querySelector(s),head=$('#appHeader'),main=$('#appMain'),modal=$('#appModal'),body=$('#modalBody');
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
const CONTACT_EMAIL='robiul20202090@proton.me';
const bn=(v=Date.now(),o={day:'numeric',month:'short'})=>new Intl.DateTimeFormat('bn-BD',o).format(new Date(v));
const initials=n=>String(n||'শিক্ষার্থী').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const avatarList=gender=>Array.isArray(window.SPT_AVATAR_CATALOG?.[gender])?window.SPT_AVATAR_CATALOG[gender]:[];
const avatarFor=s=>avatarList(s.gender).find(item=>item.id===s.avatarId)||avatarList(s.gender)[0]||null;
const avatarSrc=s=>avatarFor(s)?.src||'';
const nextAvatar=(gender,students)=>{const list=avatarList(gender);if(!list.length)return '';const used=new Set(students.filter(item=>item.gender===gender).map(item=>item.avatarId).filter(Boolean));const choices=list.filter(item=>!used.has(item.id));const pool=choices.length?choices:list;return pool[Math.floor(Math.random()*pool.length)].id;};
const blank=()=>({version:5,profile:{name:localStorage.getItem('spt-guest-name-v1')||'Guest শিক্ষক',mode:'guest'},students:[],batches:[],requests:[],activities:[],backup:{reminder:'manual',lastBackupAt:null,snoozedUntil:null}});
const student=s=>({id:s.id||uid('student'),name:String(s.name||'').trim(),gender:s.gender==='female'?'female':s.gender==='male'?'male':'',avatarId:String(s.avatarId||''),school:s.school||s.schoolName||'',grade:s.grade||'',group:s.group||'',teacherName:s.teacherName||'',note:s.note||s.message||'',subjects:(s.subjects||[]).map(x=>typeof x==='string'?x:x.name).filter(Boolean),progress:Number(s.progress||0),room:s.room||null,createdAt:s.createdAt||Date.now(),updatedAt:s.updatedAt||Date.now()});
function load(){try{const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved)return {...blank(),...saved,students:(saved.students||[]).map(student)};const old=JSON.parse(localStorage.getItem(OLD)||'null');const clean=(old?.students||[]).filter(s=>!String(s.id||'').startsWith('demo-')&&!/^আরিফা রহমান$|^রহিম হোসেন$|^করিম হাসান$/.test(String(s.name||''))).map(student);const next={...blank(),students:clean,batches:old?.batches||[],requests:old?.requests||[],activities:old?.activities||[]};localStorage.setItem(KEY,JSON.stringify(next));return next}catch(_){return blank()}}
let state=load(),view='dashboard';const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));window.SPTOnline?.queue?.()};
function note(type,details={}){state.activities.unshift({id:uid('activity'),type,details,createdAt:Date.now()});state.activities=state.activities.slice(0,30)}
function toast(message,kind='success'){const e=document.createElement('div');e.className=`toast ${kind}`;e.textContent=message;$('#toastRegion').append(e);setTimeout(()=>e.remove(),3800)}
function due(){const b=state.backup||{},p={'1d':864e5,'3d':2592e5,'1w':6048e5}[b.reminder];return !!p&&(!b.snoozedUntil||Date.now()>b.snoozedUntil)&&(!b.lastBackupAt||Date.now()-b.lastBackupAt>=p)}
function backupText(){return due()?'এখনই ব্যাকআপ নিন':state.backup?.lastBackupAt?`শেষ ব্যাকআপ: ${bn(state.backup.lastBackupAt)}`:'ব্যাকআপ সেটিংস'}
function open(markup){body.innerHTML=markup;modal.showModal()}function close(){modal.close();body.innerHTML='';body.onclick=null}
function header(){const p=state.profile||{};head.innerHTML=`<div class="header-main-row"><div class="header-brand"><img src="brand-logo.png" alt=""><div><strong>শিক্ষার্থীর অগ্রগতি</strong><span>সহজ শিক্ষক কর্মক্ষেত্র</span></div></div><div class="header-actions"><div id="headerCloudSlot"></div><button class="profile-chip" data-action="profile" aria-label="শিক্ষকের নাম"><span>${esc(initials(p.name))}</span><div><strong>${esc(p.name)}</strong><small>শিক্ষকের নাম</small></div></button><button class="header-more-button" type="button" data-action="toggle-header-menu" aria-expanded="false" aria-controls="headerMoreMenu" aria-label="আরও বিকল্প">⋮</button></div></div><nav class="header-nav" aria-label="মূল নেভিগেশন">${[['dashboard','ড্যাশবোর্ড'],['students','শিক্ষার্থী'],['batches','ব্যাচ'],['guardians','অভিভাবক']].map(([id,label])=>`<button class="nav-button ${view===id?'active':''}" data-view="${id}">${label}</button>`).join('')}</nav><section id="headerMoreMenu" class="header-overflow-menu" hidden><button class="overflow-menu-item" data-action="backup"><span>↥</span><div><b>ব্যাকআপ ও ডেটা</b><small>${backupText()}</small></div></button><div id="headerLanguageSlot"></div><div id="headerModeSlot"></div><div id="headerInstallSlot"></div></section>`}
function empty(title,copy,button=''){return `<div class="empty-state"><strong>${title}</strong><p>${copy}</p>${button}</div>`}
function launch(icon,title,count,copy,target,add,tone){return `<article class="launch-card ${tone}"><div class="launch-top"><span>${icon}</span><strong>${count}</strong></div><h2>${title}</h2><p>${copy}</p><div><button class="text-button" data-view="${target}">খুলুন →</button>${add?`<button class="mini-add" data-${add==='new-batch'?'batch-action':'action'}="${add}">＋ যোগ করুন</button>`:''}</div></article>`}
function activityList(){if(!state.activities.length)return empty('এখনও কোনো কাজ নেই','প্রথম শিক্ষার্থী যোগ করলে সাম্প্রতিক কাজ এখানে দেখা যাবে।','<button class="btn outline" data-action="new-student">শিক্ষার্থী যোগ করুন</button>');const labels={'student-created':'নতুন শিক্ষার্থী যোগ করা হয়েছে','student-updated':'শিক্ষার্থীর তথ্য পরিবর্তন হয়েছে','backup-created':'সম্পূর্ণ ডেটার ব্যাকআপ নেওয়া হয়েছে','guardian-update':'অভিভাবকের জন্য একটি আপডেট প্রস্তুত হয়েছে'};return `<div class="activity-list">${state.activities.slice(0,6).map(a=>`<article><span>${a.type==='backup-created'?'↥':a.type==='guardian-update'?'♧':'◉'}</span><div><strong>${labels[a.type]||'তথ্য হালনাগাদ হয়েছে'}${a.details?.name?` · ${esc(a.details.name)}`:''}</strong><small>${bn(a.createdAt,{day:'numeric',month:'short',hour:'numeric',minute:'numeric'})}</small></div></article>`).join('')}</div>`}
function requestRow(r){return `<article class="request-row"><span>${esc(initials(r.guardianName||'অভিভাবক'))}</span><div><strong>${esc(r.guardianName||'অভিভাবক')}</strong><small>${esc(r.studentName||r.roomName||'শিক্ষার্থী')} · ${bn(r.createdAt)}</small></div><button class="mini-add" data-action="approve-request" data-id="${esc(r.id)}">অনুমোদন</button></article>`}
function dashboard(){const pending=state.requests.filter(r=>r.status==='pending');main.innerHTML=`${due()?`<section class="backup-banner"><div><span>ব্যাকআপ মনে করিয়ে দিচ্ছি</span><strong>সম্পূর্ণ ডেটার একটি কপি নিন</strong><p>আপনার নির্ধারিত সময় পার হয়েছে।</p></div><button class="btn teal" data-action="backup">এখন ব্যাকআপ নিন</button></section>`:''}<section class="page-intro"><div><p>শিক্ষক কর্মক্ষেত্র</p><h1>আজকের প্রয়োজনীয় জায়গাগুলো এক নজরে</h1><span>একজন শিক্ষার্থী খুলে সরাসরি সাপ্তাহিক রিপোর্ট, চেকলিস্ট, অগ্রগতি ও পরীক্ষা লিখুন।</span></div><button class="btn teal" data-action="new-student">＋ শিক্ষার্থী যোগ করুন</button></section><section class="launch-grid">${launch('◉','শিক্ষার্থী',state.students.length,'নাম, রুটিন, সাপ্তাহিক শিট, চেকলিস্ট ও পরীক্ষা','students','new-student','blue')}${launch('▦','ব্যাচ',state.batches.length,'ব্যাচের পরিচয়, বিষয় ও সময়সূচি এক জায়গায়','batches','new-batch','teal')}${launch('♧','অভিভাবক',pending.length,pending.length?`${pending.length} টি অনুরোধ অপেক্ষায়`:'অনুরোধ ও শেয়ার করা রুম এখানে দেখুন','guardians',null,'ochre')}</section><section class="dashboard-columns"><article class="surface-panel"><header><div><p>সাম্প্রতিক কাজ</p><h2>সর্বশেষ পরিবর্তন</h2></div><button class="text-button" data-view="students">শিক্ষার্থী দেখুন →</button></header>${activityList()}</article><article class="surface-panel"><header><div><p>অভিভাবক</p><h2>অপেক্ষমান অনুরোধ</h2></div><button class="text-button" data-view="guardians">সব দেখুন →</button></header>${pending.length?`<div class="request-list">${pending.slice(0,3).map(requestRow).join('')}</div>`:empty('কোনো অপেক্ষমান অনুরোধ নেই','নতুন অনুরোধ এলে এখানে দেখা যাবে।')}</article></section>`}
function cards(items){if(!items.length)return empty('এখনও কোনো শিক্ষার্থী নেই','প্রথম শিক্ষার্থী যোগ করলে এখানে তার পরিচয় ও বিষয় দেখা যাবে।','<button class="btn teal" data-action="new-student">＋ শিক্ষার্থী যোগ করুন</button>');return items.map(s=>{const src=avatarSrc(s);return `<article class="student-card" data-action="open-student" data-id="${esc(s.id)}"><div class="student-card-main"><span class="student-avatar">${src?`<img src="${esc(src)}" alt="${esc(s.name)}র নির্বাচিত অবতার">`:esc(initials(s.name))}</span><div><h2>${esc(s.name)}</h2><p>${esc([s.school,s.grade,s.group].filter(Boolean).join(' · ')||'পরিচয় তথ্য যোগ করা হয়নি')}</p>${s.note?`<small>${esc(s.note)}</small>`:''}</div><span class="student-chevron">›</span></div><div class="student-tags">${s.subjects.slice(0,3).map(x=>`<span>${esc(x)}</span>`).join('')}${s.subjects.length>3?`<span>+${s.subjects.length-3}</span>`:''}</div><footer><span>${s.teacherName?`শিক্ষক: ${esc(s.teacherName)}`:'শিক্ষার্থী কর্মক্ষেত্র খুলুন'}</span><span><button class="avatar-change" data-action="change-avatar" data-id="${esc(s.id)}">অবতার বদলান</button> · ${bn(s.updatedAt)}</span></footer></article>`}).join('')}
function students(){main.innerHTML=`<section class="page-intro compact"><div><p>শিক্ষার্থী</p><h1>নাম দিয়ে খুঁজুন, তারপর কর্মক্ষেত্র খুলুন</h1><span>প্রতিটি শিক্ষার্থীর সাপ্তাহিক শিট ও সিলেবাস আলাদাভাবে সংরক্ষিত থাকে।</span></div><button class="btn teal" data-action="new-student">＋ শিক্ষার্থী যোগ করুন</button></section><section class="data-toolbar"><label class="search-field"><span>⌕</span><input id="studentSearch" type="search" placeholder="শিক্ষার্থীর নাম দিয়ে খুঁজুন"></label></section><section id="studentGrid" class="student-grid">${cards(state.students)}</section>`;$('#studentSearch').oninput=e=>{const term=e.target.value.trim().toLowerCase();$('#studentGrid').innerHTML=cards(state.students.filter(s=>s.name.toLowerCase().includes(term)))}}
function batches(){main.innerHTML=`<section class="page-intro compact"><div><p>ব্যাচ</p><h1>ব্যাচের পরিচয়, বিষয় ও সময়সূচি</h1><span>বিস্তারিত ব্যাচ কর্মক্ষেত্র পরে আলাদাভাবে পরিকল্পিত হবে।</span></div><button class="btn teal" data-batch-action="new-batch">＋ ব্যাচ যোগ করুন</button></section><section class="batch-grid">${state.batches.length?state.batches.map(b=>`<article class="batch-card"><span>▦</span><div><h2>${esc(b.name||'নামহীন ব্যাচ')}</h2><p>${esc([b.subjects?.join(' · '),b.schedule,b.note].filter(Boolean).join(' · ')||'পরিচয় তথ্য যোগ করা হয়নি')}</p></div></article>`).join(''):empty('এখনও কোনো ব্যাচ নেই','এখন শুধু ব্যাচের পরিচয় সংরক্ষণ করুন। বিস্তারিত ব্যাচ পরিকল্পনা পরে আসবে।','<button class="btn teal" data-batch-action="new-batch">＋ ব্যাচ যোগ করুন</button>')}</section>`}
function guardians(){const rooms=state.students.filter(s=>s.room),pending=state.requests.filter(r=>r.status==='pending');main.innerHTML=`<section class="page-intro compact"><div><p>অভিভাবক</p><h1>রুম, অনুরোধ ও শিক্ষক-নিয়ন্ত্রিত আপডেট</h1><span>ফোনে পুশ নয়—প্রথম ধাপে অভিভাবক রুমের ভিতরের ফিড ও ব্যাজ ব্যবহার হবে।</span></div></section><section class="dashboard-columns"><article class="surface-panel"><header><div><p>রুম</p><h2>শিক্ষার্থীভিত্তিক রুম</h2></div></header>${rooms.length?`<div class="room-list">${rooms.map(s=>`<article><div><strong>${esc(s.name)}</strong><small>কোড: ${esc(s.room.code)}</small></div><span>${s.room.feed?.length||0} আপডেট</span></article>`).join('')}</div>`:empty('কোনো রুম তৈরি হয়নি','শিক্ষার্থী কর্মক্ষেত্র থেকে রুম তৈরি করা যাবে।')}</article><article class="surface-panel"><header><div><p>অনুরোধ</p><h2>অপেক্ষমান অনুমোদন</h2></div></header>${pending.length?`<div class="request-list">${pending.map(requestRow).join('')}</div>`:empty('কোনো অপেক্ষমান অনুরোধ নেই','রুম কোড ব্যবহার করে অনুরোধ এলে এখানে দেখা যাবে।')}</article></section>`}
function contactFooter(){return `<footer class="dashboard-contact" aria-label="সহায়তা ও মতামত"><span>সহায়তা বা মতামতের জন্য:</span><a href="mailto:${CONTACT_EMAIL}">${CONTACT_EMAIL}</a></footer>`}
function render(){header();main.className=`app-main view-${view}`;({dashboard,students,batches,guardians}[view]||dashboard)();main.insertAdjacentHTML('beforeend',contactFooter());window.dispatchEvent(new Event('spt-render'))}
function studentForm(){
  open(`<section class="modal-card wide"><header><div><p>নতুন শিক্ষার্থী</p><h2>প্রয়োজনীয় তথ্য দিয়ে শুরু করুন</h2></div><button class="close-button" data-close>×</button></header><form id="studentForm"><div class="form-grid"><label>শিক্ষার্থীর নাম <b>*</b><input name="name" required maxlength="80" autofocus placeholder="নাম লিখুন"></label><label>লিঙ্গ <b>*</b><select name="gender" required><option value="">নির্বাচন করুন</option><option value="male">ছেলে</option><option value="female">মেয়ে</option></select><small>নির্বাচিত সংগ্রহ থেকে অবতার স্বয়ংক্রিয়ভাবে দেওয়া হবে।</small></label><label>শ্রেণি <select name="grade"><option value="">শ্রেণি নির্বাচন (ঐচ্ছিক)</option>${Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('')}</select></label><label>বিদ্যালয়ের নাম <input name="school" maxlength="120" placeholder="ঐচ্ছিক"></label><label>গ্রুপ <input name="group" maxlength="50" placeholder="ঐচ্ছিক"></label><label>শিক্ষকের নাম <input name="teacherName" maxlength="80" value="${esc(state.profile.name||'')}" placeholder="ঐচ্ছিক"></label><label class="full">শিক্ষকের নোট <textarea name="note" maxlength="220" placeholder="ব্যক্তিগত ছোট নোট লিখুন (ঐচ্ছিক)"></textarea></label></div><section class="subject-select"><div><p>বিষয় নির্বাচন</p><small>একাধিক NCTB বিষয় বেছে নিন অথবা নিজের বিষয় লিখুন।</small></div><div id="chosenSubjects" class="chosen-subjects"></div><div class="subject-add"><select id="nctbSubject"><option value="">বিষয় বেছে নিন</option>${SUBJECTS.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('')}</select><button class="btn outline" type="button" data-action="add-nctb">যোগ করুন</button></div><div class="subject-add"><input id="customSubject" placeholder="নিজের বিষয় লিখুন"><button class="btn outline" type="button" data-action="add-custom">যোগ করুন</button></div></section><footer><button class="btn outline" type="button" data-close>বাতিল</button><button class="btn teal" type="submit">শিক্ষার্থী যোগ করুন</button></footer></form></section>`);
  let picks=[];
  const draw=()=>$('#chosenSubjects').innerHTML=picks.length?picks.map((s,i)=>`<span>${esc(s)}<button type="button" data-action="drop-subject" data-i="${i}">×</button></span>`).join(''):'<em>এখনও কোনো বিষয় নির্বাচন করা হয়নি</em>';
  draw();
  body.onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='add-nctb'){const s=$('#nctbSubject');if(s.value&&!picks.includes(s.value))picks.push(s.value);s.value='';draw()}if(b.dataset.action==='add-custom'){const i=$('#customSubject'),v=i.value.trim();if(v&&!picks.includes(v))picks.push(v);i.value='';draw()}if(b.dataset.action==='drop-subject'){picks.splice(Number(b.dataset.i),1);draw()}if(b.dataset.action==='close')close()};
  $('#studentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget),gender=String(f.get('gender')||'');if(!avatarList(gender).length)return toast('লিঙ্গ নির্বাচন করুন।','error');const s=student({id:uid('student'),name:f.get('name'),gender,avatarId:nextAvatar(gender,state.students),grade:f.get('grade'),school:f.get('school'),group:f.get('group'),teacherName:f.get('teacherName'),note:f.get('note'),subjects:picks,createdAt:Date.now(),updatedAt:Date.now()});state.students.unshift(s);note('student-created',{name:s.name});save();close();view='students';render();toast('শিক্ষার্থী ও অবতার সফলভাবে যোগ হয়েছে।')};
}

function legacyAvatarSetup(id){
  const s=state.students.find(item=>item.id===id);if(!s)return;
  open(`<section class="modal-card"><header><div><p>পরিচয় ও অবতার ঠিক করুন</p><h2>${esc(s.name)}</h2></div><button class="close-button" data-close>×</button></header><p class="data-note">পুরোনো রেকর্ডে লিঙ্গ বা অবতার ছিল না। আমরা অনুমান করি না এবং কোনো পুরোনো ছবি রাখা হয় না। সঠিক সংগ্রহ বেছে নিতে আগে লিঙ্গ নির্বাচন করুন।</p><form id="legacyAvatarForm"><label>লিঙ্গ <b>*</b><select name="gender" required autofocus><option value="">নির্বাচন করুন</option><option value="male">ছেলে</option><option value="female">মেয়ে</option></select></label><footer><button class="btn outline" type="button" data-close>এখন নয়</button><button class="btn teal" type="submit">অবতার নির্বাচন করুন</button></footer></form></section>`);
  body.onclick=e=>{const b=e.target.closest('[data-action]');if(b?.dataset.action==='close')close()};
  $('#legacyAvatarForm').onsubmit=e=>{e.preventDefault();const gender=String(new FormData(e.currentTarget).get('gender')||'');if(!avatarList(gender).length)return toast('সঠিক লিঙ্গ নির্বাচন করুন।','error');s.gender=gender;s.avatarId=nextAvatar(gender,state.students.filter(item=>item.id!==s.id));s.updatedAt=Date.now();note('student-updated',{name:s.name});save();avatarPicker(id)};
}
function avatarPicker(id){
  const s=state.students.find(item=>item.id===id);if(!s)return;
  if(!s.gender)return legacyAvatarSetup(id);
  const list=avatarList(s.gender);if(!list.length)return toast('এই শিক্ষার্থীর জন্য অবতার সংগ্রহ পাওয়া যায়নি।','error');
  open(`<section class="modal-card wide avatar-picker-modal"><header><div><p>অবতার বদলান</p><h2>${esc(s.name)}</h2></div><button class="close-button" data-close>×</button></header><p class="data-note">নির্বাচিত লিঙ্গের সংগ্রহ থেকে একটি অবতার বেছে নিন। কোনো বাস্তব ছবি সংরক্ষণ করা হয় না।</p><div class="avatar-gallery">${list.map(item=>`<button type="button" class="avatar-tile ${item.id===s.avatarId?'selected':''}" data-action="pick-avatar" data-id="${esc(s.id)}" data-avatar="${esc(item.id)}"><img src="${esc(item.src)}" alt="অবতার"><span>${item.id===s.avatarId?'নির্বাচিত':'বেছে নিন'}</span></button>`).join('')}</div><footer><button class="btn outline" data-close>বন্ধ করুন</button></footer></section>`);
  body.onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='pick-avatar'){const target=state.students.find(item=>item.id===b.dataset.id);if(target){target.avatarId=b.dataset.avatar;target.updatedAt=Date.now();note('student-updated',{name:target.name});save();close();render();toast('অবতার পরিবর্তন হয়েছে।')}}if(b.dataset.action==='close')close()};
}
function batchForm(){open(`<section class="modal-card"><header><div><p>নতুন ব্যাচ</p><h2>ব্যাচের পরিচয় সংরক্ষণ করুন</h2></div><button class="close-button" data-close>×</button></header><form id="batchForm"><label>ব্যাচের নাম <b>*</b><input name="name" required autofocus></label><label>বিষয় <input name="subjects" placeholder="যেমন: গণিত, ইংরেজি"></label><label>সময়সূচি <input name="schedule" placeholder="যেমন: শনি ও সোম · বিকেল ৫টা"></label><label>ব্যক্তিগত নোট <textarea name="note"></textarea></label><footer><button class="btn outline" type="button" data-close>বাতিল</button><button class="btn teal">ব্যাচ যোগ করুন</button></footer></form></section>`);$('#batchForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);state.batches.unshift({id:uid('batch'),name:String(f.get('name')||'').trim(),subjects:String(f.get('subjects')||'').split(',').map(x=>x.trim()).filter(Boolean),schedule:String(f.get('schedule')||'').trim(),note:String(f.get('note')||'').trim(),createdAt:Date.now()});save();close();view='batches';render();toast('ব্যাচ যোগ হয়েছে।')}}
function openWorkspace(id){const s=state.students.find(x=>x.id===id);if(!s)return;const u=new URL('student-workspace/',location.href);[['student',s.id],['name',s.name],['grade',s.grade||'শ্রেণি উল্লেখ করা হয়নি'],['school',s.school||'বিদ্যালয়ের তথ্য যোগ করুন'],['teacher',s.teacherName||state.profile.name||'শিক্ষক'],['avatar',avatarSrc(s)],['back',location.href]].forEach(([k,v])=>u.searchParams.set(k,v));location.href=u.href}
function stamp(){const d=new Date(),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}-${z(d.getHours())}${z(d.getMinutes())}`}
function workspaceKey(id){return `scholastic-ledger.workspace.${id}.v1`}
function fullExport(){const workspaces={};state.students.forEach(s=>{try{const raw=localStorage.getItem(workspaceKey(s.id));if(raw)workspaces[s.id]=JSON.parse(raw)}catch(_){}});return {format:'student-progress-full-backup',version:1,exportedAt:new Date().toISOString(),dashboard:state,workspaces}}
function download(data,suffix=''){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),name=String(state.profile.name||'teacher').replace(/[^a-z0-9\u0980-\u09ff]+/gi,'-').slice(0,40)||'teacher';a.href=URL.createObjectURL(blob);a.download=`student-progress-${name}-${stamp()}${suffix}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportAll(safety=false){download(fullExport(),safety?'-before-restore':'');if(!safety){state.backup.lastBackupAt=Date.now();state.backup.snoozedUntil=null;note('backup-created');save();render();toast('সম্পূর্ণ ডেটার ব্যাকআপ ডাউনলোড হয়েছে。')}}
function mergeById(current,incoming){const all=new Map(current.map(x=>[x.id,x]));incoming.forEach(x=>all.set(x.id,x));return [...all.values()]}
function restoreBackup(file,mode){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result||''));if(parsed.format!=='student-progress-full-backup'||!parsed.dashboard)throw new Error('invalid');const warning=mode==='replace'?'বর্তমান ড্যাশবোর্ড ও স্থানীয় কর্মক্ষেত্র প্রতিস্থাপিত হবে। আগে নিরাপত্তা ব্যাকআপ নেওয়া হবে। আপনি কি নিশ্চিত?':'নতুন তথ্য বর্তমান তথ্যের সঙ্গে একত্র করা হবে। আগে নিরাপত্তা ব্যাকআপ নেওয়া হবে। আপনি কি নিশ্চিত?';if(!confirm(warning))return;exportAll(true);const incoming={...blank(),...parsed.dashboard,students:(parsed.dashboard.students||[]).map(student)};state=mode==='replace'?incoming:{...state,students:mergeById(state.students,incoming.students),batches:mergeById(state.batches,incoming.batches||[]),requests:mergeById(state.requests,incoming.requests||[]),activities:[...(incoming.activities||[]),...state.activities].slice(0,30)};Object.entries(parsed.workspaces||{}).forEach(([id,data])=>localStorage.setItem(workspaceKey(id),JSON.stringify(data)));save();close();render();toast('ব্যাকআপ থেকে তথ্য পুনরুদ্ধার হয়েছে।')}catch(_){toast('এই ফাইলটি সঠিক সম্পূর্ণ ব্যাকআপ নয়।','error')}};reader.readAsText(file)}
function backupPanel(){const b=state.backup||{};open(`<section class="modal-card wide"><header><div><p>ব্যাকআপ ও ডেটা</p><h2>সম্পূর্ণ ডেটা নিরাপদে রাখুন</h2></div><button class="close-button" data-close>×</button></header><p class="data-note">এই ব্যাকআপে সব শিক্ষার্থী, ব্যাচ, ড্যাশবোর্ড তথ্য এবং প্রতিটি শিক্ষার্থীর স্থানীয় কর্মক্ষেত্র থাকবে। শেষ সম্পূর্ণ ব্যাকআপ: <b>${b.lastBackupAt?bn(b.lastBackupAt,{day:'numeric',month:'long',hour:'numeric',minute:'numeric'}):'এখনও নেওয়া হয়নি'}</b></p><section class="backup-actions"><button class="btn teal" type="button" data-action="download-backup">সম্পূর্ণ ডেটা ডাউনলোড করুন</button><label class="reminder-label">ব্যাকআপ রিমাইন্ডার<select id="backupReminder"><option value="manual">ম্যানুয়াল / বন্ধ</option><option value="1d">প্রতি ১ দিন</option><option value="3d">প্রতি ৩ দিন</option><option value="1w">প্রতি ১ সপ্তাহ</option></select></label>${due()?'<button class="mini-add" type="button" data-action="snooze-backup">আগামীকাল মনে করান</button>':''}</section><section class="restore-area"><p>ডেটা ইমপোর্ট / রিস্টোর</p><small>ইমপোর্টের আগে একটি নিরাপত্তা ব্যাকআপ স্বয়ংক্রিয়ভাবে ডাউনলোড হবে।</small><div class="restore-choice"><label><input type="radio" name="restoreMode" value="merge" checked> বর্তমান ডেটার সঙ্গে একত্র করুন</label><label><input type="radio" name="restoreMode" value="replace"> বর্তমান ডেটা প্রতিস্থাপন করুন</label></div><input id="restoreFile" type="file" accept="application/json,.json"></section><footer><button class="btn outline" data-close>বন্ধ করুন</button></footer></section>`);$('#backupReminder').value=b.reminder||'manual';body.onclick=e=>{const x=e.target.closest('[data-action]');if(!x)return;if(x.dataset.action==='download-backup')exportAll();if(x.dataset.action==='snooze-backup'){state.backup.snoozedUntil=Date.now()+864e5;save();close();render();toast('আগামীকাল আবার মনে করানো হবে।')}if(x.dataset.action==='close')close()};$('#backupReminder').onchange=e=>{state.backup.reminder=e.target.value;state.backup.snoozedUntil=null;save();render();toast('ব্যাকআপ রিমাইন্ডার সংরক্ষিত হয়েছে।')};$('#restoreFile').onchange=e=>{const file=e.target.files?.[0],mode=$('input[name="restoreMode"]:checked').value;if(file)restoreBackup(file,mode)}}
window.__openDashboardBackup=backupPanel;
window.SPTDashboard={getState:()=>state,setState:next=>{state={...blank(),...next,students:(next.students||[]).map(student)};localStorage.setItem(KEY,JSON.stringify(state));render()},fullExport,openWorkspace,render,toast,close,uid};
function profilePanel(){const current=String(state.profile?.name||'').trim();open(`<section class="modal-card"><header><div><p>শিক্ষকের পরিচয়</p><h2>নাম ঠিক করুন</h2></div><button class="close-button" data-close>×</button></header><p class="data-note">এই ধাপে শুধু শিক্ষকের নাম রাখা হবে। কোনো ছবি বা অতিরিক্ত প্রোফাইল তথ্য প্রয়োজন নেই।</p><form id="teacherProfileForm"><label>শিক্ষকের নাম<input name="teacherName" maxlength="80" required autofocus value="${esc(current)}" placeholder="নাম লিখুন"></label><footer><button class="btn outline" type="button" data-close>বাতিল</button><button class="btn teal" type="submit">সংরক্ষণ করুন</button></footer></form></section>`);body.onclick=e=>{if(e.target.closest('[data-close]'))close()};$('#teacherProfileForm').onsubmit=e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('teacherName')||'').trim();if(!name)return;state.profile={...(state.profile||{}),name};save();close();render();toast('শিক্ষকের নাম সংরক্ষণ হয়েছে।')}}
function placeholder(title,copy){open(`<section class="modal-card"><header><div><p>${title}</p><h2>পরবর্তী ধাপে প্রস্তুত করা হচ্ছে</h2></div><button class="close-button" data-close>×</button></header><p class="data-note">${copy}</p><footer><button class="btn teal" data-close>ঠিক আছে</button></footer></section>`)}
document.addEventListener('click',event=>{if(modal.open&&body.contains(event.target))return;const button=event.target.closest('[data-action]');if(!button){const menu=$('#headerMoreMenu');if(menu&&!menu.hidden){menu.hidden=true;head.querySelector('[data-action="toggle-header-menu"]')?.setAttribute('aria-expanded','false')}return}if(button.dataset.action==='toggle-header-menu'){event.preventDefault();event.stopImmediatePropagation();const menu=$('#headerMoreMenu'),open=menu.hidden;menu.hidden=!open;button.setAttribute('aria-expanded',String(open));return}if(button.dataset.action==='profile'){event.preventDefault();event.stopImmediatePropagation();profilePanel();return}if(button.dataset.action==='backup'){event.preventDefault();event.stopImmediatePropagation();backupPanel();return}},true);
document.addEventListener('click',e=>{if(modal.open&&body.contains(e.target))return;const b=e.target.closest('[data-action],[data-view]');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();return}if(b.dataset.action==='new-student')studentForm();if(b.dataset.action==='new-batch')batchForm();if(b.dataset.action==='open-student')openWorkspace(b.dataset.id);if(b.dataset.action==='change-avatar')avatarPicker(b.dataset.id);if(b.dataset.action==='backup')placeholder('ব্যাকআপ ও ডেটা','সম্পূর্ণ ডেটা ডাউনলোড, ইমপোর্ট/রিস্টোর, এবং রিমাইন্ডার সেটিংস এখন যুক্ত হচ্ছে।');if(b.dataset.action==='profile')placeholder('পরিচয়','Guest / Offline তথ্য ও ব্যাকআপের সতর্কতা এখানে নিয়ন্ত্রণ করা যাবে।');if(b.dataset.action==='approve-request'){const r=state.requests.find(x=>x.id===b.dataset.id);if(r){r.status='approved';save();render();toast('অভিভাবকের অনুরোধ অনুমোদন হয়েছে।')}}});modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.open)close()});setTimeout(()=>{$('#startup').classList.add('leaving');head.classList.remove('hidden');main.classList.remove('hidden');render()},620);

window.addEventListener('spt-dashboard-state-changed',()=>{state=load();if(view==='dashboard'||view==='batches')render();});
